#!/usr/bin/env node
// Embeds examples/context-demo into the CLI so `diditbreak init --demo` works
// from a single-file npm install. examples/context-demo is the source of truth;
// a CLI test fails if the embedded copy drifts from it.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const source = join(root, "examples/context-demo");
const target = join(root, "packages/cli/src/demo/demo-project.ts");

// Files the agent must never see: the edit itself and the demo's own docs.
const EXCLUDE = new Set(["CLAUDE.bloated.md", "README.md"]);

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "runs" || entry.name === "node_modules") continue;
      out.push(...(await walk(path)));
    } else if (!EXCLUDE.has(entry.name)) {
      out.push(relative(source, path));
    }
  }
  return out.sort();
}

const files = {};
for (const path of await walk(source)) {
  files[path] = await readFile(join(source, path), "utf-8");
}
const edit = await readFile(join(source, "CLAUDE.bloated.md"), "utf-8");

await writeFile(
  target,
  `// Generated by scripts/sync-demo.mjs from examples/context-demo. Do not edit.\n\n` +
    `/** The demo project as committed: a short, correct CLAUDE.md. */\n` +
    `export const DEMO_FILES: Record<string, string> = ${JSON.stringify(files, null, 2)};\n\n` +
    `/** The uncommitted edit under test: team-wiki guidelines pasted into CLAUDE.md. */\n` +
    `export const DEMO_EDITED_CLAUDE_MD = ${JSON.stringify(edit)};\n`
);
console.log(`Embedded ${Object.keys(files).length} files into ${relative(root, target)}`);
